name: javadoc

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build
        uses: gradle/gradle-build-action@v2.4.2
        with:
          arguments: build

      - name: Publish
        uses: s0/git-publish-subdir-action@master
        env:
          REPO: self
          BRANCH: javadoc
          FOLDER: ../build/docs/javadoc
          CLEAR_GLOBS_FILE: "./.github/workflows/.clear-target-files"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_branch: javadoc
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/docs/javadoc